# -*- coding: utf-8 -*-
"""Algoritmo de Caprekar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x8yTzw0pG4nPq5IceiBCzQ8urZaqF2As
"""

#Algoritmo de Kaprekar

valido = 0

while valido == 0:

    entrada = input("Digite um número de 4 dígitos positivo: ")

    #verificador de número inteiro
    if entrada >= "0" and entrada <= "9999":

        num = int(entrada)

    #verificador de 4 digitos
        if num >= 1000 and num <= 9999:

            #separando dígitos
            d1 = num // 1000
            resto = num % 1000

            d2 = resto // 100
            resto = resto % 100

            d3 = resto // 10
            d4 = resto % 10

            cont1 = 1
            cont2 = 1
            cont3 = 1
            cont4 = 1

            if d1 == d2: cont1 = cont1 + 1
            if d1 == d3: cont1 = cont1 + 1
            if d1 == d4: cont1 = cont1 + 1

            if d2 == d1: cont2 = cont2 + 1
            if d2 == d3: cont2 = cont2 + 1
            if d2 == d4: cont2 = cont2 + 1

            if d3 == d1: cont3 = cont3 + 1
            if d3 == d2: cont3 = cont3 + 1
            if d3 == d4: cont3 = cont3 + 1

            if d4 == d1: cont4 = cont4 + 1
            if d4 == d2: cont4 = cont4 + 1
            if d4 == d3: cont4 = cont4 + 1

            if cont1 >= 3 or cont2 >= 3 or cont3 >= 3 or cont4 >= 3:
                print("Erro, somente 2 números podem repetir.\n")
            else:
                valido = 1

        else:
            print("Erro: Digite somente números inteiros e de 4 digitos.\n")

    else:
        print("Erro: Digite somente números inteiros e de 4 digitos.\n")

#Processamento do Programa

contador = 0


while num != 6174:

    #separando dígitos
    d1 = num // 1000
    resto = num % 1000

    d2 = resto // 100
    resto = resto % 100

    d3 = resto // 10
    d4 = resto % 10

    milhar = d1
    centena = d2
    dezena = d3
    unidade = d4

    # trocando a ordem dos números
    if milhar < centena:
        temp = milhar
        milhar = centena
        centena = temp

    if milhar < dezena:
        temp = milhar
        milhar = dezena
        dezena = temp

    if milhar < unidade:
        temp = milhar
        milhar = unidade
        unidade = temp

    if centena < dezena:
        temp = centena
        centena = dezena
        dezena = temp

    if centena < unidade:
        temp = centena
        centena = unidade
        unidade = temp

    if dezena < unidade:
        temp = dezena
        dezena = unidade
        unidade = temp


    #montando os números
    ndd = milhar * 1000 + centena * 100 + dezena * 10 + unidade
    ndc = unidade * 1000 + dezena * 100 + centena * 10 + milhar


    resultado = ndd - ndc

    contador = contador + 1

    print("Iteração", contador, ":", ndd, "-", ndc, "=", resultado)

    num = resultado

#Saída
print("Constante de Kaprekar atingida em", contador, "iterações.")

